### ISSUE TITLE
Please an example about usage, like a CommandBase?

### ISSUE THREAD

**Issue by azhe403** [TgBotFramework/TgBotFramework.Examples#1]

**Comment by Fedorus** [comment]
I'm little busy today... you can look in my personal repo's repo TgBotFramework it contains examples also... it may be little bit different cuz i'm migrating code from there...

**Comment by Fedorus** [comment]
https://github.com/TgBotFramework/TgBotFramework.Examples/blob/master/SimpleConsole/Program.cs#L35
